"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { Logo } from "@/components/site/Logo";
import { createClient } from "@/lib/supabase/client";
import { getSupabaseConfigurationMessage, isSupabaseConfigured } from "@/lib/supabase/config";

export default function LoginPage() { const [error, setError] = useState(""); const [pending, setPending] = useState(false); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); if (!isSupabaseConfigured) { setError(`Dịch vụ đăng nhập chưa được cấu hình. ${getSupabaseConfigurationMessage() || "Hãy kiểm tra biến môi trường Supabase."}`); setPending(false); return; } const form = new FormData(event.currentTarget); try { const { error: authError } = await createClient().auth.signInWithPassword({ email: String(form.get("email")), password: String(form.get("password")) }); if (authError) { setError("Không thể đăng nhập. Hãy kiểm tra email và mật khẩu, hoặc cấu hình Email provider trong Supabase."); return; } const nextPath = new URLSearchParams(window.location.search).get("next"); const isSafePath = Boolean(nextPath) && nextPath!.startsWith("/") && !nextPath!.startsWith("//");
    // Ensure the newly written authentication cookie reaches proxy.ts.
    window.location.assign(isSafePath ? nextPath! : "/admin");
  } catch { setError("Không thể kết nối đến Supabase. Hãy kiểm tra URL, anon key và trạng thái project."); } finally { setPending(false); } }
  return <main className="grid min-h-screen place-items-center bg-[#f7f9fc] p-5"><div className="w-full max-w-md"><Logo/><div className="mt-8 rounded-md border border-[#e6eaf0] bg-white p-7 shadow-[0_16px_45px_rgba(16,24,40,.08)] sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-md bg-[#edf0ff] text-[#d72626]"><LockKeyhole size={20}/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#d72626]">Khu vực tòa soạn</p><h1 className="display mt-2 text-4xl font-bold">Đăng nhập</h1><p className="mt-3 text-sm leading-6 text-[#667085]">Sử dụng tài khoản quản trị Supabase của bạn để tiếp tục.</p><form onSubmit={onSubmit} className="mt-7 grid gap-4"><label className="grid gap-1.5 text-sm font-bold">Email<input name="email" type="email" autoComplete="email" required className="rounded-sm border border-[#d0d5dd] px-3 py-3 font-normal outline-none transition focus:border-[#d72626] focus:ring-2 focus:ring-[#e8ecff]"/></label><label className="grid gap-1.5 text-sm font-bold">Mật khẩu<input name="password" type="password" autoComplete="current-password" required className="rounded-sm border border-[#d0d5dd] px-3 py-3 font-normal outline-none transition focus:border-[#d72626] focus:ring-2 focus:ring-[#e8ecff]"/></label>{error && <p role="alert" className="rounded-lg bg-[#fef3f2] px-3 py-2 text-sm text-[#b42318]">{error}</p>}<button disabled={pending} className="mt-1 inline-flex items-center justify-center gap-2 rounded-sm bg-[#101828] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#344054] disabled:opacity-60 active:scale-[.98]">{pending ? "Đang xác thực…" : <>Đăng nhập<ArrowRight size={16}/></>}</button></form></div><Link href="/" className="mt-5 inline-block text-sm font-bold text-[#667085] hover:text-[#d72626]">← Về trang công khai</Link></div></main>; }
